### ISSUE TITLE
quarkjs程序使用phonegap打包后不能运行

### ISSUE THREAD

**Issue by niceboy** [quark-dev-team/quarkjs#19]
quarkjs程序使用phonegap打包后不能运行。资源都不会被加载，使用了quarkjs的示例程序测试也是这样。是不支持吗？

**Comment by flashlizi** [comment]
这个可能是资源加载路径的问题。我没测试过phonegap。

**Comment by niceboy** [comment]
确实是资源加载路径的大小写问题。Thanks
