### ISSUE TITLE
MouseEvent和TouchEvent的对象所含属性有区别

### ISSUE THREAD

**Issue by skyblue** [quark-dev-team/quarkjs#3]
touch对象没有e.x e.y

**Comment by flashlizi** [comment]
在quark的事件处理函数onEvent中，可以得到参数e的如下属性：
e.eventX - 事件发生的舞台x坐标
e.eventY - 事件发生的舞台y作品
e.eventTarget - 事件发生目标对象
e.lastEventTarget - 上一个事件目标对象

（没有e.x或e.y的属性）

请参考：https://github.com/quark-dev-team/quarkjs/wiki/Handle-Events

**Comment by sunlt** [comment]
TouchEvent 是没有 X、Y的  因为touch可以是多根手指
详细的参考 apple dev的文档
