### ISSUE TITLE
Graphics绘制简单形状的边框问题

### ISSUE THREAD

**Issue by timcui** [quark-dev-team/quarkjs#4]
在利用Graphics绘制简单形状（如矩形）时，调用lineStyle(0)方法无法达到无边框的效果，看源码是这样写的：

this._addAction(["lineWidth", (this.lineWidth = thickness || 1)]);

即在设置thickness为0时会失败，实际上lineWidth为1。

不知道是否还有其他的方式可以去掉简单形状的边框？

**Comment by flashlizi** [comment]
Hi, 这个bug已经修复了。如果没有调用lineStyle方法，则不会出现边框。
